
import {
  ClerkProvider
} from '@clerk/nextjs';
import { Geist, Geist_Mono } from "next/font/google";
import Header from "../components/header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children}) {
  return (
     <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <main> <footer className="bg-blue-100 py-12"><div className="container mx-auto px-4 text-center text-gray-600">
          <p>Made by Sophiya Khadka</p>
        </div>
          </footer></main>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
